import { MatchInfo } from "src/app/services/api-service/api.service";
export const GAMES:MatchInfo[] = [/*
    {

        players:2,
        bots:1,
        timeout:10.0,
        args : {},
        id: "hHhtyyGg",
        name: "Lobby1",
        game: "royalur",
        running: false,
        time: 10,
        connected: {},
        spectators: 3,
        password: false,
        verified: false,
    },
    {

        players:3,
        bots:0,
        timeout:100.0,
        args : {},
        id: "oOibv4tDe",
        name: "Lobby2",
        game: "roshambo",
        running: true,
        time: 30,
        connected: {},
        spectators: 2,
        password: true,
        verified: false,
    },
    {

        players:2,
        bots:2,
        timeout:10.0,
        args : {},
        id: "oacwrqu3256",
        name: "Lobby3",
        game: "roshambo",
        running: false,
        time: 30,
        connected: {},
        spectators: 2,
        password: true,
        verified: true,
    },
    {

        players:2,
        bots:2,
        timeout:10.0,
        args : {},
        id: "oacwrqu3256",
        name: "Lobby3",
        game: "roshambo",
        running: false,
        time: 30,
        connected: {},
        spectators: 2,
        password: true,
        verified: true,
    },
    {

        players:2,
        bots:2,
        timeout:10.0,
        args : {},
        id: "oacwrqu3256",
        name: "Lobby3",
        game: "roshambo",
        running: false,
        time: 30,
        connected: {},
        spectators: 2,
        password: true,
        verified: true,
    },
    {

        players:2,
        bots:2,
        timeout:10.0,
        args : {},
        id: "oacwrqu3256",
        name: "Lobby3",
        game: "roshambo",
        running: false,
        time: 30,
        connected: {},
        spectators: 2,
        password: true,
        verified: true,
    },
    {

        players:2,
        bots:2,
        timeout:10.0,
        args : {},
        id: "oacwrqu3256",
        name: "Lobby3",
        game: "roshambo",
        running: false,
        time: 30,
        connected: {},
        spectators: 2,
        password: true,
        verified: true,
    },*/
]