import { Game } from "src/app/Game";

export const GAMES:Game[] = [
    {
        id:"ftgHyo0",
        name:"Lobby 1",
        verified:true,
        game:"royalur",
        spectators:10,
        players:25,
        maxplayers:25,
        timeout:100,
        password:true,
        current:true,
        time:200,
    },
    {
        id:"hHdeTTr",
        name:"Lobby 2",
        verified:false,
        game:"royalur",
        spectators:20,
        players:20,
        maxplayers:25,
        timeout:200,
        password:true,
        current:false,
        time:200,
    },
    {
        id:"grwdfc",
        name:"Santa's lobby",
        verified:true,
        game:"royalur",
        spectators:20,
        players:20,
        maxplayers:25,
        timeout:200,
        password:true,
        current:false,
        time:200,
    },
    {
        id:"fgyjte",
        name:"Hello match",
        verified:false,
        game:"royalur",
        spectators:20,
        players:20,
        maxplayers:25,
        timeout:200,
        password:true,
        current:true,
        time:200,
    },
    {
        id:"gThopO",
        name:"Match lobby",
        verified:false,
        game:"royalur",
        spectators:20,
        players:20,
        maxplayers:25,
        timeout:200,
        password:false,
        current:true,
        time:20,
    },
    {
        id:"cDffRd",
        name:"Match lobby",
        verified:false,
        game:"royalur",
        spectators:20,
        players:20,
        maxplayers:25,
        timeout:200,
        password:false,
        current:true,
        time:2,
    },
    {
        id:"cDffRd",
        name:"Match lobby",
        verified:false,
        game:"royalur",
        spectators:20,
        players:20,
        maxplayers:25,
        timeout:200,
        password:false,
        current:true,
        time:200,
    },
    {
        id:"cDffRd",
        name:"Match lobby",
        verified:false,
        game:"royalur",
        spectators:20,
        players:20,
        maxplayers:25,
        timeout:200,
        password:false,
        current:true,
        time:200,
    },
    {
        id:"cDffRd",
        name:"Match lobby",
        verified:false,
        game:"royalur",
        spectators:20,
        players:20,
        maxplayers:25,
        timeout:200,
        password:true,
        current:true,
        time:20,
    },
    {
        id:"cDffRd",
        name:"Match lobby",
        verified:false,
        game:"royalur",
        spectators:20,
        players:20,
        maxplayers:25,
        timeout:200,
        password:false,
        current:true,
        time:200,
    },
    {
        id:"cDffRd",
        name:"Match lobby",
        verified:false,
        game:"royalur",
        spectators:20,
        players:20,
        maxplayers:25,
        timeout:200,
        password:false,
        current:true,
        time:20,
    },
]